# Base info
name: Tencent Cloud Rust Gateway
port: 8089
# description: 

description2: |-
    Â©          ï¼¿ï¼¿                ____ _                 _ 
           ï¼ï¼    >             / ____| |               | |                
           |  ğŸ‘ |ğŸ‘ l            | |    | | ___  _   _  __| | __ _ _ __ __ _ 
          ï¼;ãƒŸ_x ãƒŸ            | |    | |/ _ \| | | |/ _` |/ _` | '__/ _` |
         /     ğŸ€               | |____| | (_) | |_| | (_| | (_| | | | (_| |
        /  ãƒ½    ï¾‰               \_____|_|\___/ \__,_|\__,_|\__,_|_|  \__, |
        â”‚  |  | |                                                      __/ |
    ï¼ï¿£|  |  | |              == ä¸ä¼šåšé¥­çš„æ­Œæ‰‹ä¸æ˜¯å¥½ç¨‹åºå‘˜ ==       |___/
    | (ï¿£ãƒ½ï¼¿ãƒ½_)_)                         ğŸ¦€ ğŸ¦€ ğŸ¦€ ğŸ¦€ ğŸ¦€ ğŸ¦€ 
    ï¼¼äºŒã¤                    ---------------------------------------------



description: |-
  . ./\                           ____ _                 _ 
    ( /   ğŸ‘ ğŸ‘    ()             / ____| |               | |  
     \\ __| |__  /             | |    | | ___  _   _  __| | __ _ _ __ __ _    
      \/   "   \/              | |    | |/ _ \| | | |/ _` |/ _` | '__/ _` |
     /-|       |-\             | |____| | (_) | |_| | (_| | (_| | | | (_| |
     / /-`---'-\ \              \_____|_|\___/ \__,_|\__,_|\__,_|_|  \__, |
      /         \                                                     __/ |            
  ğŸ’§ ğŸŒŠ ğŸ’§ ğŸŒŠ ğŸ’§ ğŸŒŠ ğŸ’§        == ä¸ä¼šåšé¥­çš„æ­Œæ‰‹ä¸æ˜¯å¥½ç¨‹åºå‘˜ ==       |___/
  

account_url: ${ACCOUNT_URL:http://47.114.92.162:7301/inner/self/info}
ticket_secret: ${TICKET_SECRET:iloveyou}
timeout: ${TIMEOUT:5}

# Mysql Config
mysql:
  host: ${DB_HOST:127.0.0.1}
  port: ${DB_PORT:3306}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:AbCd12#$}
  database: ${DB_DATABASE:dims}

# redis config
redis_uri: ${REDIS_URL:redis://zhwell@127.0.0.1:8020/10}
